# Dependencies
highlighter:      pygments

# Setup
title:            Tom Fletcher
tagline:          'A Jekyll theme'
description:      'Astrophysics PhD Student at UCL'
url:              https://tomjf.github.io
baseurl:          /

author:
  name:           'Tom Fletcher'
  url:            https://twitter.com/tomfletcher0

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tomjf/tomjf.github.io
